"""Build notebooks/02_lag_analysis.ipynb programmatically and execute it."""
import nbformat as nbf
from pathlib import Path

nb = nbf.v4.new_notebook()
cells = []

cells.append(nbf.v4.new_markdown_cell(
    "# Phase 2 — Lag analysis (CCF)\n"
    "\n"
    "For each of DE, GB, RU, we compute the cross-correlation function (CCF) "
    "between monthly arrivals and (a) the market's Google-Trends keyword and "
    "(b) the corresponding real exchange rate, over lags **-6 to +6 months**.\n"
    "\n"
    "_Sign convention used throughout:_ a **positive lag k** means the regressor "
    "leads arrivals by k months — that is, $\\rho(k) = \\text{corr}(x_{t-k}, y_t)$, "
    "so the regressor's value k months ago is correlated with arrivals today. A "
    "**negative lag** means the regressor lags arrivals.\n"
    "\n"
    "**Caveat — raw-series CCF.** Tourism arrivals are dominated by a strong "
    "annual seasonal cycle; Google-Trends search intent has the same seasonal "
    "shape. The CCF on the raw series will largely reflect this shared "
    "seasonality, which biases the peak-correlation lag toward 0. The raw-series "
    "peaks below are a first pass; the YoY-CCF section further down repeats the "
    "analysis on $\\Delta_{12} \\log$-transformed series so the remaining "
    "correlation reflects deviations from each series' typical seasonal path."
))

cells.append(nbf.v4.new_code_cell(
    "import matplotlib.pyplot as plt\n"
    "import numpy as np\n"
    "import pandas as pd\n"
    "import seaborn as sns\n"
    "from pathlib import Path\n"
    "\n"
    "ROOT = Path('..').resolve()\n"
    "FIG_DIR = ROOT / 'outputs' / 'figures'\n"
    "FIG_DIR.mkdir(parents=True, exist_ok=True)\n"
    "\n"
    "sns.set_theme(style='whitegrid', context='notebook')\n"
    "\n"
    "df = pd.read_csv(ROOT / 'data' / 'processed' / 'master_monthly.csv',\n"
    "                 index_col=0, parse_dates=True)\n"
    "df.index.name = 'date'\n"
    "\n"
    "MARKETS = {\n"
    "    'DE': {'trends': 'trends_DE_Türkei_Urlaub',  'real_fx': 'real_EUR_TRY', 'color': '#1f4e79'},\n"
    "    'GB': {'trends': 'trends_GB_Turkey_holiday', 'real_fx': 'real_GBP_TRY', 'color': '#2e7d32'},\n"
    "    'RU': {'trends': 'trends_RU_Турция_отдых',   'real_fx': 'real_RUB_TRY', 'color': '#7e57c2'},\n"
    "}\n"
    "MAX_LAG = 6"
))

cells.append(nbf.v4.new_markdown_cell(
    "## Cross-correlation helper\n"
    "\n"
    "`ccf_two_sided` computes Pearson correlation between $x_{t-k}$ and $y_t$ "
    "for $k = -L, \\ldots, +L$. Inputs are aligned to their overlapping period "
    "and NaNs are dropped pairwise. The asymptotic 95% white-noise band at "
    "each lag is $\\pm 1.96 / \\sqrt{N_{\\text{eff}}(k)}$ where $N_{\\text{eff}}(k) = N - |k|$ "
    "is the number of usable observations at that lag."
))

cells.append(nbf.v4.new_code_cell(
    "def ccf_two_sided(x: pd.Series, y: pd.Series, max_lag: int = MAX_LAG):\n"
    "    \"\"\"Return (lags, ccf_values, conf_band, n_overlap).\n"
    "    \n"
    "    Positive lag k: x leads y by k months (corr of x_{t-k} with y_t).\n"
    "    Negative lag k: x lags y by |k| months.\n"
    "    \"\"\"\n"
    "    pair = pd.concat([x.rename('x'), y.rename('y')], axis=1).dropna()\n"
    "    n = len(pair)\n"
    "    xv = (pair['x'] - pair['x'].mean()) / pair['x'].std()\n"
    "    yv = (pair['y'] - pair['y'].mean()) / pair['y'].std()\n"
    "    \n"
    "    lags = np.arange(-max_lag, max_lag + 1)\n"
    "    vals = np.full(len(lags), np.nan)\n"
    "    for i, k in enumerate(lags):\n"
    "        if k >= 0:\n"
    "            a = xv.iloc[:n - k].values\n"
    "            b = yv.iloc[k:].values\n"
    "        else:\n"
    "            a = xv.iloc[-k:].values\n"
    "            b = yv.iloc[:n + k].values\n"
    "        if len(a) > 2:\n"
    "            vals[i] = np.corrcoef(a, b)[0, 1]\n"
    "    \n"
    "    conf = 1.96 / np.sqrt(np.maximum(n - np.abs(lags), 1))\n"
    "    return lags, vals, conf, n\n"
    "\n"
    "\n"
    "def plot_ccf(ax, lags, vals, conf, n, title, color):\n"
    "    ax.bar(lags, vals, color=color, alpha=0.85, edgecolor='white')\n"
    "    ax.plot(lags, conf, color='#cc4c4c', ls='--', lw=1, label='95% band')\n"
    "    ax.plot(lags, -conf, color='#cc4c4c', ls='--', lw=1)\n"
    "    ax.axhline(0, color='black', lw=0.5)\n"
    "    ax.axvline(0, color='gray', lw=0.5, ls=':')\n"
    "    ax.set_xlabel('Lag k (months)  — k>0: x leads arrivals')\n"
    "    ax.set_ylabel('Correlation')\n"
    "    ax.set_ylim(-1.05, 1.05)\n"
    "    ax.set_title(f'{title}  (N={n})')\n"
    "    ax.legend(loc='lower left', fontsize=9, framealpha=0.95)"
))

# Per-market sections.
for mkt, spec in [
    ("DE", {"trends": "trends_DE_Türkei_Urlaub",  "real_fx": "real_EUR_TRY"}),
    ("GB", {"trends": "trends_GB_Turkey_holiday", "real_fx": "real_GBP_TRY"}),
    ("RU", {"trends": "trends_RU_Турция_отдых",   "real_fx": "real_RUB_TRY"}),
]:
    cells.append(nbf.v4.new_markdown_cell(
        f"## {mkt}\n"
        f"\n"
        f"CCF of `{spec['trends']}` and `{spec['real_fx']}` versus "
        f"`arrivals_total`."
    ))
    cells.append(nbf.v4.new_code_cell(
        f"mkt = '{mkt}'\n"
        f"spec = MARKETS[mkt]\n"
        f"\n"
        f"lags_t, vals_t, conf_t, n_t = ccf_two_sided(df[spec['trends']],  df['arrivals_total'])\n"
        f"lags_f, vals_f, conf_f, n_f = ccf_two_sided(df[spec['real_fx']], df['arrivals_total'])\n"
        f"\n"
        f"fig, axes = plt.subplots(1, 2, figsize=(13, 4.5))\n"
        f"plot_ccf(axes[0], lags_t, vals_t, conf_t, n_t,\n"
        f"         f'{{mkt}} — Trends vs. arrivals', spec['color'])\n"
        f"plot_ccf(axes[1], lags_f, vals_f, conf_f, n_f,\n"
        f"         f'{{mkt}} — real FX vs. arrivals', spec['color'])\n"
        f"fig.tight_layout()\n"
        f"fig.savefig(FIG_DIR / f'lag_{{mkt}}_ccf.png', dpi=150)\n"
        f"plt.show()"
    ))

# Task 8 — RU pre/post February 2022 split.
cells.append(nbf.v4.new_markdown_cell(
    "## RU: pre/post February 2022\n"
    "\n"
    "The Russia–Ukraine war is a plausible structural break in Russian tourism "
    "patterns: pre-2022 the flow is holiday-driven, post-2022 it plausibly "
    "includes relocations. A full-sample CCF spanning that break averages the "
    "two regimes together, so the panel below splits the RU CCF into "
    "pre-2022-02 and post-2022-02 subsamples. The post-2022 window is short, "
    "which widens the 95% white-noise band."
))

cells.append(nbf.v4.new_code_cell(
    "pre  = df.loc[:'2022-01-01']\n"
    "post = df.loc['2022-02-01':]\n"
    "\n"
    "ru_col = MARKETS['RU']['trends']\n"
    "\n"
    "lags_pre,  vals_pre,  conf_pre,  n_pre  = ccf_two_sided(pre[ru_col],  pre['arrivals_total'])\n"
    "lags_post, vals_post, conf_post, n_post = ccf_two_sided(post[ru_col], post['arrivals_total'])\n"
    "\n"
    "fig, axes = plt.subplots(1, 2, figsize=(13, 4.5))\n"
    "plot_ccf(axes[0], lags_pre,  vals_pre,  conf_pre,  n_pre,\n"
    "         'RU — Trends vs arrivals (up to 2022-01)', MARKETS['RU']['color'])\n"
    "plot_ccf(axes[1], lags_post, vals_post, conf_post, n_post,\n"
    "         'RU — Trends vs arrivals (2022-02 onward)', MARKETS['RU']['color'])\n"
    "fig.tight_layout()\n"
    "fig.savefig(FIG_DIR / 'lag_RU_split_ccf.png', dpi=150)\n"
    "plt.show()\n"
    "\n"
    "def _peak(lags, vals):\n"
    "    absvals = np.abs(vals)\n"
    "    if np.all(np.isnan(absvals)):\n"
    "        return None, None\n"
    "    i = int(np.nanargmax(absvals))\n"
    "    return int(lags[i]), round(float(vals[i]), 3)\n"
    "\n"
    "pk_pre  = _peak(lags_pre,  vals_pre)\n"
    "pk_post = _peak(lags_post, vals_post)\n"
    "print(f'pre  (N={n_pre}) : peak lag {pk_pre[0]}, rho={pk_pre[1]}')\n"
    "print(f'post (N={n_post}): peak lag {pk_post[0]}, rho={pk_post[1]}')"
))

cells.append(nbf.v4.new_markdown_cell(
    "**Reading the split.** Executed peaks: pre-2022 (2016-01 → 2022-01, "
    "N = 73) peaks at lag +1 with ρ = +0.722 — Russian search intent leads "
    "arrivals by one month in the pre-war holiday regime. Post-2022-02 "
    "(N = 45) peaks at lag −5 with ρ = −0.724 — search now lags arrivals by "
    "five months and moves in the opposite direction. The sign flip between "
    "the two sub-periods is the structural break; the small post-2022 "
    "sample widens the 95% band to roughly ±0.29, so individual lag peaks "
    "should be read as suggestive rather than tight, but the direction "
    "reversal is unmissable at that magnitude. The most plausible reading is "
    "that post-war Russian flows into Turkey stopped being vacation traffic "
    "and started being relocations, decoupling from search intent."
))

# Task 6 — YoY CCF section.
cells.append(nbf.v4.new_markdown_cell(
    "## YoY CCF (seasonally adjusted lead/lag)\n"
    "\n"
    "The raw CCF above measures the shared annual cycle; this section repeats "
    "the analysis on $\\Delta_{12} \\log$ changes so the remaining correlation "
    "reflects deviations from each series' typical seasonal path (i.e., the "
    "part of arrivals not explained by \"it is July\")."
))

cells.append(nbf.v4.new_code_cell(
    "def yoy_log_safe(s):\n"
    "    s = s.replace(0, np.nan)\n"
    "    return np.log(s) - np.log(s.shift(12))\n"
    "\n"
    "yoy_arrivals = yoy_log_safe(df['arrivals_total'])\n"
    "\n"
    "yoy_results = {}\n"
    "fig, axes = plt.subplots(1, 3, figsize=(18, 4.5))\n"
    "for ax, mkt in zip(axes, ['DE', 'GB', 'RU']):\n"
    "    spec = MARKETS[mkt]\n"
    "    yoy_trends = yoy_log_safe(df[spec['trends']])\n"
    "    lags, vals, conf, n = ccf_two_sided(yoy_trends, yoy_arrivals)\n"
    "    plot_ccf(ax, lags, vals, conf, n,\n"
    "             f'{mkt} — YoY Trends vs YoY arrivals', spec['color'])\n"
    "    yoy_results[mkt] = (lags, vals, conf, n)\n"
    "fig.tight_layout()\n"
    "fig.savefig(FIG_DIR / 'lag_yoy_ccf.png', dpi=150)\n"
    "plt.show()\n"
    "\n"
    "yoy_rows = []\n"
    "for mkt, (lags, vals, conf, n) in yoy_results.items():\n"
    "    absvals = np.abs(vals)\n"
    "    if np.all(np.isnan(absvals)):\n"
    "        continue\n"
    "    i = int(np.nanargmax(absvals))\n"
    "    yoy_rows.append({\n"
    "        'market':    mkt,\n"
    "        'peak_lag':  int(lags[i]),\n"
    "        'rho_peak':  round(float(vals[i]), 3),\n"
    "        'n':         n,\n"
    "    })\n"
    "yoy_peaks = pd.DataFrame(yoy_rows)\n"
    "yoy_peaks"
))

# Summary table (raw + yoy).
cells.append(nbf.v4.new_markdown_cell(
    "## Summary — lag of peak correlation\n"
    "\n"
    "For each (market, regressor, transform) tuple: the lag $k^*$ at which "
    "$|\\rho(k)|$ is maximised, the value $\\rho(k^*)$, the 95% band edge at "
    "$k^*$, and whether the peak is statistically distinct from white noise. "
    "The `transform` column is `raw` for the raw-series CCFs above and `yoy` "
    "for the YoY-CCF rows added by the new section."
))

cells.append(nbf.v4.new_code_cell(
    "rows = []\n"
    "for mkt, spec in MARKETS.items():\n"
    "    for kind, col in [('Trends', spec['trends']), ('real FX', spec['real_fx'])]:\n"
    "        lags, vals, conf, n = ccf_two_sided(df[col], df['arrivals_total'])\n"
    "        absvals = np.abs(vals)\n"
    "        if np.all(np.isnan(absvals)):\n"
    "            continue\n"
    "        i = int(np.nanargmax(absvals))\n"
    "        rows.append({\n"
    "            'market':    mkt,\n"
    "            'regressor': kind,\n"
    "            'column':    col,\n"
    "            'transform': 'raw',\n"
    "            'n_overlap': n,\n"
    "            'peak_lag':  int(lags[i]),\n"
    "            'rho_peak':  round(float(vals[i]), 3),\n"
    "            'conf_95':   round(float(conf[i]), 3),\n"
    "            'significant': bool(abs(vals[i]) > conf[i]),\n"
    "        })\n"
    "\n"
    "# YoY variants: Trends only (real FX would need CPI on both sides).\n"
    "for mkt, (lags, vals, conf, n) in yoy_results.items():\n"
    "    absvals = np.abs(vals)\n"
    "    if np.all(np.isnan(absvals)):\n"
    "        continue\n"
    "    i = int(np.nanargmax(absvals))\n"
    "    rows.append({\n"
    "        'market':    mkt,\n"
    "        'regressor': 'Trends',\n"
    "        'column':    MARKETS[mkt]['trends'],\n"
    "        'transform': 'yoy',\n"
    "        'n_overlap': n,\n"
    "        'peak_lag':  int(lags[i]),\n"
    "        'rho_peak':  round(float(vals[i]), 3),\n"
    "        'conf_95':   round(float(conf[i]), 3),\n"
    "        'significant': bool(abs(vals[i]) > conf[i]),\n"
    "    })\n"
    "\n"
    "summary = pd.DataFrame(rows)\n"
    "summary"
))

cells.append(nbf.v4.new_code_cell(
    "summary.to_csv(ROOT / 'outputs' / 'lag_summary.csv', index=False)\n"
    "print(f\"→ outputs/lag_summary.csv\")"
))

cells.append(nbf.v4.new_markdown_cell(
    "## What the YoY CCF says\n"
    "\n"
    "Executed peaks (see `yoy_peaks` above, `lag_yoy_ccf.png`, and the full-shape "
    "printout below): DE peaks at lag −6 with ρ = +0.619, GB at lag 0 with "
    "ρ = +0.462, RU at lag 0 with ρ = +0.463, all on N = 106. The full shape is:\n"
    "\n"
    "- **DE**: broad, monotonically-decreasing positive correlation from lag −6 "
    "  through lag +2, all above the 95% white-noise band; a clean +1 lead does "
    "  not survive. Lag +1 is still significant (ρ = +0.289) but is not the peak. "
    "  The two YoY series co-move over a slow window rather than through a "
    "  one-month lead structure.\n"
    "- **GB**: near-symmetric shape around **lag 0** (peak ρ = +0.462, with "
    "  lag ±1 both above the band). The old raw-CCF claim of a one-month "
    "  UK lead was driven by shared seasonality; once removed, GB search and "
    "  arrivals move essentially contemporaneously.\n"
    "- **RU (full sample, YoY)**: peaks at lag 0 with ρ = +0.463. The raw "
    "  CCF's negative peak was mixing two regimes; the pre/post split above "
    "  shows the real story — pre-2022 positive peak at lag +1 with ρ = +0.72 "
    "  (search leads arrivals in the holiday regime); post-2022-02 negative "
    "  peak at lag −5 with ρ = −0.72 (arrivals rise while search falls, "
    "  consistent with relocation-driven flows).\n"
    "\n"
    "**Bottom line.** Once seasonality is removed, Google Trends does **not** "
    "cleanly lead arrivals by one month for either DE or GB in the "
    "full-sample YoY CCF; the +1 lead in the raw series was largely the "
    "shared summer cycle. The Russia inversion, however, is not a "
    "seasonality artefact: it is a genuine 2022 regime change, visible in "
    "the raw pre/post split and in the sign flip between the two "
    "sub-periods."
))

nb["cells"] = cells

out_path = Path(__file__).parent / "02_lag_analysis.ipynb"
out_path.write_text(nbf.writes(nb))
print(f"wrote {out_path}")
